### ISSUE TITLE
Question | RNA file _waldec  and _import | cache

### ISSUE THREAD

**Issue by fas3r** [betagouv/rna_as_api#20]
Bonjour, 

Je souhaiterai mettre en place un provisioning automatique qui recupere les fichiers `rna_import_***.zip` et `rna_waldec_***.zip` chaque 1er du mois (et s'ils ne sont pas dispo, postponer toutes les 6/12/24h). 

Est ce que je peux les telecharger directement depuis `https://media.interieur.gouv.fr` en respectant le format `https://media.interieur.gouv.fr/rna/rna_***_20180801.zip` ou il est preferable de  parser les balises `<a>` [quand dans le fichier suivant ](https://github.com/etalab/rna_as_api/blob/8e874ee70606a5ae04aa379c9637f24cc00cc2e2/app/interactors/get_last_monthly_stock_links.rb) afin de recuperer les liens et ainsi telecharger les fichiers depuis `https://media.interieur.gouv.fr` ?

Derniere question, est ce qu'il est possible qu'une association disposant d'un SIRET/SIREN n'apparaisse pas dans les fichiers RNA ? (pour savoir si je devrai inclure aussi la [base sirene](https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/) de facon similaire)

Merci d'avance.

**Comment by Samuelfaure** [comment]
Bonjour !

1/ A priori vous pouvez faire les deux méthodes, j'ai personnellement choisi de parser data.gouv pour obtenir les liens, pour plusieurs raisons :
a) Fiabilité des équipes data.gouv
b) Je ne suis pas sûr qu'il y ait un index des fichiers dispo sur le ministère de l'intérieur, alors que depuis data.gouv on peut s'assurer de toujours connaitre les derniers fichiers disponibles

2/ A priori le RNA doit recenser TOUTES les associations, nous n'avons pas encore eu connaissance d'associations manquantes.
A priori, la base SIRENE devrait recenser TOUTES les associations disposant d'un siret/siren.
Attention, le siret/siren est souvent mal renseigné dans RNA, et le numéro RNA est souvent mal renseigné dans SIRENE.

Si vous n'avez besoin que des associations, l'api RNA devrait répondre à vos besoins.

En vous remerciant pour votre interet, je fermerais cette issue dans une semaine si vous n'avez pas d'autres questions

**Comment by fas3r** [comment]
Bonjour @Samuelfaure , 

1/ Effectivement je pense que votre maniere est la plus judicieuse.

2/ Oui j'ai vu ca.

Si jamais vous avez des conseillez pour le reformattage des donnees comme les addresses postal, je suis preneurs sinon vous pouvez fermer le ticket, je devrai trouver la reponse dans les sources ^^

Merci pour votre retour.

**Comment by Samuelfaure** [comment]
l'API renvoie les données brutes du RNA, qui sont souvent de qualité très médiocres, hélas je n'ai pas vraiment de conseil pour en améliorer la qualité..
