### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by SebPARMENTIER** [betagouv/rna_as_api#45]
Bonjour,

Depuis samedi 14 août 2021, impossible d'obtenir de résultat en raison d'une erreur 500. Pouvez-vous nous informer de la situation actuelle et d'une éventuelle date de rétablissement svp ?

D'avance, merci.

**Comment by skelz0r** [comment]
Bonjour,

Nous avons eu en effet un souci de production ce week-end, cela a été fixé ce matin.

Désolé pour le dérangement.
