### ISSUE TITLE
Supprimer les accents dans la recherche textuelle

### ISSUE THREAD

**Issue by maximepvrt** [betagouv/rna_as_api#52]
La recherche est sensible aux accents, ainsi, si nous mettons les accents sur une association qui s'est déclarée sans nous n'avons pas de résultat et inversement.

Pour cela il existe l'extension PG `CREATE EXTENSION unaccent;`

**Comment by maximepvrt** [comment]
🙏 @Haelle @Samuelfaure @am-beta

**Comment by am-beta** [comment]
Pensez-vous qu'il faut ajouter cette extension côté Ansible ? j'y ai pas réfléchi donc je n'ai pas trop d'avis.

**Comment by Samuelfaure** [comment]
@am-beta J'ai fait une PR pour ajouter l'extension à la création; Pas besoin de toucher à Ansible.

Je viens d'installer l'extension sur l'API; à priori ça ne fonctionne pas pour le moment. Je vais tenter de relancer un export.

**Comment by Samuelfaure** [comment]
Je pense qu'il faut toucher aux réglages de SOLR. Je fais une nouvelle PR.

**Comment by Samuelfaure** [comment]
OK ça fonctionne. Je met à jour l'API vite fait et je ferme.

**Comment by maximepvrt** [comment]
Super nouvelle cette mise à jour de l'API ! Merci infiniment ! 🙏 🤩
