### ISSUE TITLE
Utiliser la mise à jour quotidienne dur RNA sur l'API 

### ISSUE THREAD

**Issue by maximepvrt** [betagouv/rna_as_api#58]
@Samuelfaure, Serait-il possible de voir avec le Ministère de l'Intérieur / Djepva pour accéder à la mise à jour quotidienne du référentiel RNA comme cette API https://entreprise.api.gouv.fr/catalogue/djepva/associations_open_data ?

Cette API ne proposant pas d'API de recherche et étant lié à l'API Entreprise qui requière une accréditation, il ne semble que je ne puisse pas y avoir accès en tant qu'entreprise (Benevolt propose aux associations après validation de leur RNA de trouver des bénévoles sur notre plateforme)

Merci d'avance,

**Comment by Samuelfaure** [comment]
@maximepvrt En effet, API Entreprise n'est ouverte qu'aux entreprises "chargée d'une mission de service public" ou bien "délégataire de service public" et à priori vous ne semblez pas dans l'une de ces situations.

Pour obtenir les mises à jour quotidiennes de la DJEPVA, je vois 2 solutions:

1/ Implémenter un CRON job quotidien pour directement aller piocher les informations sur l'API ouverte DJEPVA

2/ Faire une demande auprès de Data.gouv et/ou le MI/DJEPVA pour que les fichiers de mises à jour quotidiennes soient ajoutées sur leur site, ou que le fichier RNA soit téléversé sur Data.gouv non pas mensuellement mais quotidiennement

Pour le 1/ je ne peux pas vous aider hélas, car mon contrat de mission actuel ne me permet pas de passer beaucoup de temps sur ce projet. Vous pouvez cependant tenter les développements par votre propre équipe.

Pour le 2/ vous pouvez tenter de contacter [Data.gouv](https://support.data.gouv.fr/) afin d'exprimer ce besoin, ou contacter directement le responsable des données RNA (MI) [sur cette page](https://www.data.gouv.fr/en/datasets/repertoire-national-des-associations/#/discussions)

Je ferme l'issue ici, avec mes excuses pour ne pas pouvoir mieux répondre à votre problème.

**Comment by maximepvrt** [comment]
@Samuelfaure Merci beaucoup pour ces différentes informations / solutions. Je vais continuer à creuser ce point avec les différentes équipes Data.gouv, le MI/DJEPVA.
